--NOMBRE Y PRESUPUESTO DE LAS PELICULAS ESTRENADAS DESPUES DEL 10/10/1992
SELECT NOMBRE, PRESUPUESTO || ' MILLONES' AS PRESUPUESTO 
FROM PELICULA
--TO_DATE: CONVERTIR A FECHA - RECIBE LA CADENA CON LA FECHA Y EL FORMATO
WHERE FECHA_ESTRENO > TO_DATE('10/10/1992', 'DD/MM/YYYY');

--CODIGO, NOMBRE Y FECHA DE ESTRENO DE LAS PELICULAS CON CALIFICACION EN EL INTERVALO [2.1, 4.3]
SELECT CODIGO, NOMBRE, FECHA_ESTRENO
FROM PELICULA
WHERE CALIFICACION BETWEEN 2.1 AND 4.3;
--WHERE CALIFICACION >= 2.1 AND CALIFICACION <= 4.3 (OTRA OPCION)

--NOMBRE DEL ACTOR, NOMBRE DE LA PELICULA EN LA QUE PARTICIPA, ANIO DE LA PELICULA Y NOMBRE DEL DIRECTOR.
--CONSIDERE SOLO ACTORES DE NACIONALIDAD PERUANA.

--OLD-STYLE
SELECT PA.NOMBRE, PE.NOMBRE, PE.FECHA_ESTRENO, PD.NOMBRE
FROM PERSONA PA, PERSONA PD, ACTOR_PELICULA AP, PELICULA PE
WHERE PA.CODIGO = AP.COD_ACTOR
AND PE.CODIGO = AP.COD_PELICULA
AND PE.COD_DIRECTOR = PD.CODIGO
AND PA.NACIONALIDAD = 'PERUANA';

--ANSI-SQL: TAREA
--****************

--TODOS LOS CODIGOS DE PELICULAS DONDE ACTUA LA PERSONA DE CODIGO 100
SELECT COD_PELICULA FROM ACTOR_PELICULA WHERE COD_ACTOR = 100;

--PARA OBTENER LOS DATOS DE LAS PELICULAS: SUBCONSULTAS
SELECT * FROM PELICULA WHERE CODIGO IN (SELECT COD_PELICULA FROM ACTOR_PELICULA WHERE COD_ACTOR = 100);

--TODOS LOS ACTORES QUE ACTUAN EN LA PELICULA DE CODIGO 300
SELECT COD_ACTOR FROM ACTOR_PELICULA WHERE COD_PELICULA = 300;

--DATOS DE GENERO ASOCIADOS A LA PELICULA DE CODIGO 200
SELECT * FROM GENERO WHERE CODIGO IN (
    SELECT COD_GENERO FROM GENERO_PELICULA WHERE COD_PELICULA = 200
);
