--CONSULTAS
SELECT * FROM USUARIO;
SELECT * FROM CAMPEONATO;

SELECT * FROM CAMPEONATO
WHERE FECHA_FIN - FECHA_INICIO = 6;


--OBTENER NOMBRE USUARIO, EL NOMBRE DEL CAMPEONATO Y EL RESULTADO
SELECT  U.NOMBRE AS NOMBRE_USUARIO, C.NOMBRE AS NOMBRE_CAMPEONATO, P.RESULTADO
FROM PARTICIPACION P, USUARIO U, CAMPEONATO C
WHERE P.COD_USUARIO = U.CODIGO
AND P.COD_CAMPEONATO = C.CODIGO;

--OBTENER NOMBRE USUARIO, NOMBRE DEL CLUB, EL NOMBRE DEL CAMPEONATO Y EL RESULTADO
SELECT U.NOMBRE AS NOMBRE_USUARIO, CL.NOMBRE AS NOMBRE_CLUB, C.NOMBRE AS NOMBRE_CAMPEONATO, P.RESULTADO
FROM PARTICIPACION P, USUARIO U, CAMPEONATO C, CLUB CL
WHERE P.COD_USUARIO = U.CODIGO
AND P.COD_CAMPEONATO = C.CODIGO
AND U.COD_EQUIPO = CL.COD_CLUB;

--CAMPEONATOS (NOMBRE DEL CAMPEONATO, FECHA INICIO) DONDE HAYAN PARTICIPADO JUGADORES DEL CLUB "AVENGERS".
SELECT U.NOMBRE, C.NOMBRE, C.FECHA_INICIO
FROM USUARIO U, CAMPEONATO C, PARTICIPACION P, CLUB CL
WHERE CL.COD_CLUB = U.COD_EQUIPO
AND U.CODIGO = P.COD_USUARIO
AND P.COD_CAMPEONATO = C.CODIGO
AND CL.NOMBRE = 'AVENGERS';



--NOMBRE DE LOS CAMPEONATOS QUE INICIARON DESPUES DEL 01/01/2019
SELECT * FROM CAMPEONATO
WHERE FECHA_INICIO > TO_DATE('01/01/2019', 'DD/MM/YYYY');

--MUESTRE DATOS DE LOS CAMPEONATOS QUE INICIARON ANTES DEL 02/05/2015.
--CONSIDERE NOMBRE DE CAMPEONATO Y NOMBRE DE LOS PARTICIPANTES.
SELECT C.NOMBRE AS NOMBRE_CAMPEONATO, U.NOMBRE AS NOMBRE_PARTICIPANTE
FROM CAMPEONATO C, PARTICIPACION P, USUARIO U
WHERE C.CODIGO = P.COD_CAMPEONATO
AND P.COD_USUARIO = U.CODIGO
AND C.FECHA_INICIO < TO_DATE('02/05/2015', 'DD/MM/YYYY');


--El correo del usuario Cesar Perales esta incorrecto. La direccion es CPERALESF@HOTMAIL.COM
UPDATE CORREO_USUARIO
SET DIRECCION_CORREO = 'CPERALESF@HOTMAIL.COM'
WHERE COD_USUARIO = 200
AND DIRECCION_CORREO = 'CPERALES@HOTMAIL.COM';


--El usuario Juan Perez ya no utiliza su direccion JPEREZ@YAHOO.ES
DELETE FROM CORREO_USUARIO
WHERE COD_USUARIO = 100
AND DIRECCION_CORREO = 'JPEREZ@YAHOO.ES';

--USUARIOS QUE PERTENECEN A LOS EQUIPOS 1, 2, o 5
SELECT * FROM USUARIO WHERE COD_EQUIPO IN (1, 2, 5);

--USUARIOS QUE NO TIENEN CLUB ASOCIADO
SELECT * FROM USUARIO WHERE COD_EQUIPO IS NULL;

--USUARIOS QUE NO PERTENEZCAN AL CLUB DE CODIGO 40
SELECT * FROM USUARIO WHERE COD_EQUIPO <> 40;

--CAMPEONATOS QUE SE HAYAN INICIADO ENTRE EL 2/10/2005 Y EL 10/4/2021
SELECT * FROM CAMPEONATO
WHERE FECHA_INICIO BETWEEN TO_DATE('02/10/2005', 'DD/MM/YYYY') AND TO_DATE('10/04/2021', 'DD/MM/YYYY');

--USUARIOS CUYO NOMBRE EMPIECE CON J
SELECT * FROM USUARIO
WHERE NOMBRE LIKE 'J%';

--USUARIOS CUYA SEGUNDA LETRA DEL NOMBRE SEA E
SELECT * FROM USUARIO
WHERE NOMBRE LIKE '_E%';

--FUNCIONES DE CADENAS
SELECT LPAD(CODIGO, 8, '0'), UPPER(NOMBRE), LOWER(NOMBRE), INITCAP(NOMBRE), LENGTH(NOMBRE)
FROM USUARIO;

--FUNCIONES NUMERICAS

SELECT TRUNC((5 * 6 + 12) / 11, 2) FROM DUAL;
SELECT ROUND((10 + 11) / 2) FROM DUAL;
SELECT POWER(2, 3), SQRT(2) FROM DUAL;

--FUNCIONES DE FECHA
SELECT FECHA_INICIO, TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA_INICIO)) FROM CAMPEONATO;

SELECT FECHA_INICIO, ADD_MONTHS(FECHA_INICIO, 12) FROM CAMPEONATO;

SELECT FECHA_INICIO, TO_CHAR(FECHA_INICIO, 'DD MONTH, YYYY') FROM CAMPEONATO;

SELECT FECHA_INICIO, TO_CHAR(FECHA_INICIO, 'YEAR') FROM CAMPEONATO;

--EJEMPLOS ALTER TABLE
/*
ALTER TABLE CAMPEONATO ADD FECHA_FIN DATE;
ALTER TABLE CAMPEONATO DROP COLUMN FECHA;
ALTER TABLE CAMPEONATO ADD FECHA_INICIO DATE;
ALTER TABLE CAMPEONATO RENAME COLUMN FECHA_INICIO TO FECHA_INI;
*/
