--5)
UPDATE USUARIO 
SET OPERADOR_TELEFONO = 'VODAFONE',
    NUMERO_TELEFONO = '9849495933'
WHERE CODIGO = 350;

--6)
DELETE FROM CAMPEONATO
WHERE EXTRACT(YEAR FROM FECHA_INICIO) = 2018;
--ALTENATIVA TO_DATE(FECHA_INICIO, 'YYYY') = '2018'

--7
SELECT U.NOMBRE, CU.DIRECCION_CORREO, C.NOMBRE
FROM USUARIO U
INNER JOIN CORREO_USUARIO CU
ON U.CODIGO = CU.COD_USUARIO
INNER JOIN PARTICIPACION P
ON P.COD_USUARIO = U.CODIGO
INNER JOIN CAMPEONATO C
ON C.CODIGO = P.COD_CAMPEONATO;

--8)
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME, D.DEPARTMENT_NAME, J.JOB_TITLE
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
WHERE SYSDATE - HIRE_DATE > 3000;

--9)
SELECT  J.JOB_TITLE, 
        MAX(E.SALARY) AS MAX_SALARY, 
        MIN(E.SALARY) AS MIN_SALARY,
        TRUNC(AVG(E.SALARY), 2) AS AVG_SAL
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
WHERE E.DEPARTMENT_ID NOT IN (90, 60)
AND COMMISSION_PCT IS NULL
AND SYSDATE - HIRE_DATE > (SELECT AVG(SYSDATE - HIRE_DATE) FROM EMPLOYEES)
GROUP BY J.JOB_TITLE;

--10)
SELECT C.COURSE_NO, C.DESCRIPTION, SE.SECTION_NO, SE.LOCATION, I.FIRST_NAME || ' ' || I.LAST_NAME AS INSTRUCTOR
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN SECTION SE
ON E.SECTION_ID = SE.SECTION_ID
INNER JOIN COURSE C
ON SE.COURSE_NO = C.COURSE_NO
INNER JOIN INSTRUCTOR I
ON SE.INSTRUCTOR_ID = I.INSTRUCTOR_ID
WHERE E.STUDENT_ID = 100;

--11)
SELECT  C.COURSE_NO, C.DESCRIPTION, 
        SE.SECTION_NO, I.FIRST_NAME || ' ' || I.LAST_NAME AS INSTRUCTOR,
        SE.CAPACITY - (SELECT COUNT(*) FROM ENROLLMENT WHERE SECTION_ID = SE.SECTION_ID) AS "AVAILABLE SEATS"
FROM SECTION SE
INNER JOIN COURSE C
ON SE.COURSE_NO = C.COURSE_NO
INNER JOIN INSTRUCTOR I
ON SE.INSTRUCTOR_ID = I.INSTRUCTOR_ID
WHERE C.COURSE_NO IN(101, 102, 106);





