--CADENAS: CONCATENACION

--OBTENGA EL NOMBRE COMPLETO Y EL SALARIO DE TODOS LOS EMPLEADOS
SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME, SALARY FROM EMPLOYEES;

--COMPARACION - IGUALDAD
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven';

--COMPARACION - LIKE

--MUESTRE LOS DATOS DE TODOS LOS EMPLEADOS CUYO APELLIDO EMPIECE CON 'Ch'
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE 'Ch%';

--MUESTRE LOS DATOS DE TODOS LOS EMPLEADOS CUYA SEGUNDA LETRA DEL NOMBRE SEA 'e'
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_e%';

--MUESTRE LOS DATOS DE TODOS LOS EMPLEADOS CUYA SEGUNDA Y CUARTA LETRA DEL NOMBRE SEA 'e'
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_e_e%';

--MUESTRE LOS DATOS DE LOS EMPLEADOS CUYO APELLIDO TERMINE EN 'er'
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%er';

--MAYUSCULAS, MINUSCULAS, PRIMERA LETRA EN MAYUSCULAS
SELECT FIRST_NAME, UPPER(FIRST_NAME), LOWER(FIRST_NAME), INITCAP('hola ' || FIRST_NAME)
FROM EMPLOYEES;

--SUBCADENA, LONGITUD DE CADENA, BUSQUEDA EN CADENA
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 2, 5), LENGTH(FIRST_NAME), INSTR(FIRST_NAME, 'a')
FROM EMPLOYEES;

--MUESTRE EL CODIGO DE EMPLEADO COMPLETADO HASTA 5 DIGITOS (CON CEROS A LA IZQUIERDA)
--Y EL NOMBRE DEL EMPLEADO COMPLETADO HASTA 80 CARACTERES (CON *)
SELECT LPAD(EMPLOYEE_ID, 5, '0'), RPAD(FIRST_NAME, 80, ' ')
FROM EMPLOYEES;

--FUNCIONES NUMERICAS: ROUND, TRUNC
SELECT AVG(SALARY), ROUND(AVG(SALARY)), ROUND(AVG(SALARY), 1), TRUNC(AVG(SALARY)), TRUNC(AVG(SALARY), 1)
FROM EMPLOYEES;

--OPERACIONES ARITMETICAS CON FECHA

--CANTIDAD DE DIAS ENTRE EL 10/05/2022 Y EL 02/05/2022
SELECT TO_DATE('10/05/2022', 'DD/MM/YYYY') - TO_DATE('02/05/2022', 'DD/MM/YYYY')
FROM DUAL;

--ANTIGUEDAD EN DIAS (CUMPLIDOS) DE CADA EMPLEADO DE LA EMPRESA
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, TRUNC(SYSDATE - HIRE_DATE) FROM EMPLOYEES;

--LA FECHA ACTUAL, LA FECHA HACE 71 DIAS Y LA FECHA DENTRO DE 332 DIAS
SELECT SYSDATE, SYSDATE - 71, SYSDATE + 332
FROM DUAL;

--LA FECHA DENTRO DE EXACTAMENTE 14 MESES
SELECT ADD_MONTHS(SYSDATE, 14)
FROM DUAL;

--ANTIGUEDAD EN MESES (REDONDEE) DE CADA EMPLEADO EN LA EMPRESA
SELECT LAST_NAME, SYSDATE, HIRE_DATE, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE))
FROM EMPLOYEES;

--ANTIGUEDAD EN ANIOS (CUMPLIDOS) DE CADA EMPLEADO EN LA EMPRESA
SELECT LAST_NAME, SYSDATE, HIRE_DATE, TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12)
FROM EMPLOYEES;

--FUNCIONES TRUNC Y ROUND PARA FECHAS
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL;
SELECT ROUND(SYSDATE + 10, 'MONTH') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') FROM DUAL;

--FORMATOS DE FECHA

--EXTRAER MES Y ANIO DE LA FECHA ACTUAL
SELECT TO_CHAR(SYSDATE, 'MM-YYYY') FROM DUAL;

--EXTAER EL DIA DE LA SEMANA
SELECT TO_CHAR(SYSDATE, 'DAY') FROM DUAL;

--HORA DEL SISTEMA HORA:MINUTO:SEGUNDO
SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS') FROM DUAL;

--FUNCIONES DE GRUPO
SELECT COUNT(*), MAX(SALARY), MIN(SALARY), TRUNC(AVG(SALARY), 2), TRUNC(STDDEV(SALARY), 2) 
FROM EMPLOYEES;

--GROUP BY
--MUESTRE EL SALARIO PROMEDIO PROMEDIO POR DEPARTAMENTO. ORDENE POR NOMBRE DE DPTO
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, TRUNC(AVG(SALARY), 2)
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME;

--MUESTRE LA CANTIDAD DE EMPLEADOS POR ROL DE EMPLEADO (REALICE UN RANKING)
SELECT J.JOB_ID, J.JOB_TITLE, COUNT(*)
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE, J.JOB_ID
ORDER BY COUNT(*) DESC;

--HAVING
--ELABORE UN LISTADO CON LA CANTIDAD DE EMPLEADOS, SALARIO MAXIMO Y SALARIO MINIMO
--POR CIUDAD. CONSIDERE SOLAMENTE A LAS CIUDADES CON MAS DE 5 EMPLEADOS.
SELECT L.CITY, COUNT(*), MAX(E.SALARY), MIN(E.SALARY)
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
GROUP BY L.CITY
HAVING COUNT(*) > 5;


--SUBCONSULTAS

--EN LA CLAUSULA WHERE
--Muestre los empleados que pertezcan a departamentos cuyo nombre
--comience con 'A'
SELECT * 
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME LIKE 'A%');

--EN LA SENTENCIA SELECT
--Muestre el apellido del empleado, su salario y el salario promedio de su departamento
SELECT  E.LAST_NAME, 
        E.SALARY,
        E.DEPARTMENT_ID,
        (SELECT TRUNC(AVG(SALARY), 2) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID) AVG_SAL
FROM EMPLOYEES E;

--EN LA CLAUSULA FROM
--Muestre el apellido del empleado, su salario, el salario maximo, minimo y promedio de su departamento

SELECT E.LAST_NAME, E.SALARY, SAL_DPT.MAX_SAL, SAL_DPT.MIN_SAL, TRUNC(SAL_DPT.AVG_SAL, 2)
FROM 
EMPLOYEES E
INNER JOIN (
                SELECT  DEPARTMENT_ID, 
                        MAX(SALARY) AS MAX_SAL, 
                        MIN(SALARY) AS MIN_SAL, 
                        AVG(SALARY) AS AVG_SAL
                FROM EMPLOYEES
                GROUP BY DEPARTMENT_ID

            ) SAL_DPT
ON E.DEPARTMENT_ID = SAL_DPT.DEPARTMENT_ID;





--MUESTRE EL CODIGO, APELLIDO Y SALARIO DE LOS EMPLEADOS QUE FUERON CONTRATADOS DESPUES
--DEL 1/1/1992. CONSIDERE SOLO A AQUELLOS QUE PERTENEZCAN A LOS DEPARTAMENTOS 100, 110, 120 Y 130.
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > TO_DATE('01/01/1992', 'DD/MM/YYYY')
AND DEPARTMENT_ID IN(100, 110, 120, 130);


--MUESTRE LA LISTA DE EMPLEADOS QUE TIENEN COMISION. MUESTRE SOLO APELLIDO,
--SALARIO Y FECHA DE CONTRATACION EN FORMATO 'DD-MM-YYYY'
SELECT LAST_NAME, SALARY, TO_CHAR(HIRE_DATE, 'DD-MM-YYYY') 
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;


--MUESTRE LOS DATOS DE LOS EMPLEADOS QUE PERTENEZCAN A DEPARTAMENTOS CUYO NOMBRE
--INICIE CON LA LETRA 'S'. CONSIDERE NOMBRE COMPLETO Y NOMBRE DE DEPARTAMENTO.
--MUESTRE EL NOMBRE COMPLETO EN MAYUSCULA
SELECT UPPER(E.FIRST_NAME || ' ' || E.LAST_NAME) AS NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME LIKE 'S%';


--MUESTRE EL APELLIDO, EL SALARIO Y LA CIUDAD EN LA QUE TRABAJAN
--LOS EMPLEADOS CON UN SALARIO EN EL INTERVALO <5000, 10000]. EXCLUYA
--DEL LISTADO A LOS EMPLEADOS DEL DEPARTAMENTO 'Shipping'

SELECT E.LAST_NAME, E.SALARY, L.CITY
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.SALARY > 5000
AND E.SALARY <= 10000
AND D.DEPARTMENT_NAME <> 'Shipping';

